repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.4
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
-   repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.7
    hooks:
      # Ensure the uv lock file is up to date
      - id: uv-lock
        files: pyproject.toml
        args: [--project, python]
